export default [
  {
    type: 'datetime-local',
    name: 'date',
    label: 'Fecha:',    
    id:'registryDate',
    onChange: 'onChangeDate',
    placeholder: 'dd/mm/yyyy',
    defaultValue: null,
  },
  {
    type: 'text',
    name: 'account',
    label: 'Cuenta:',
    id:'registryAccount',
    renderMethod:'renderAccounts',
    onChange: 'onChange',
    placeholder: 'enter the account here',
    defaultValue: null,
  },
  {
    type: 'text',
    name: 'name',
    label: 'Nombre:',
    id:'registryName',
    onChange: 'onChange',
    placeholder: 'enter the name here',
    defaultValue: null,
  },
  {
    type: 'number',
    name: 'debit',
    label: 'Debito:',
    id:'registryDebit',
    onChange: 'onChange',
    placeholder: '0.00',
    defaultValue: null,
  },
  {
    type: 'number',
    name: 'credit',
    label: 'Credito:',
    id:'registryCredit',
    onChange: 'onChange',
    placeholder: '0.00',
    defaultValue: null,
  },
  {
    type: 'number',
    name: 'dolar',
    label: 'Dolar:',
    id:'registryDolar',
    onChange: 'onChange',
    placeholder: '0.00',
    defaultValue: null,
  },
];